SELECT DISTINCT *  WHERE {
 ?poi a dbo:PopulatedPlace.
 ?poi rdfs:label ?label.
 FILTER(lang(?label)=?lang).
 ?poi rdfs:comment ?comment.
 FILTER(lang(?comment)=?lang).
 OPTIONAL{
  ?poi geo:lat ?lat.
  ?poi geo:long ?long.
 }
}
LIMIT 10